# Generated by Django 6.0.2 on 2026-03-02 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('authors', models.CharField(max_length=255)),
                ('thumbnail', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('reading', 'Reading'), ('completed', 'Completed'), ('want_to_read', 'Want to Read'), ('dnf', 'Did not finished')], default='want_to_read', max_length=20)),
                ('date_started', models.DateField(null=True)),
                ('date_finished', models.DateField(null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
