# Generated by Django 6.0.2 on 2026-03-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
