# Generated by Django 6.0.2 on 2026-03-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userbook_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='authors',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
