# Generated by Django 6.0.2 on 2026-03-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userbook_authors_alter_userbook_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
